# Generated by Django 4.2.4 on 2023-08-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='available',
            new_name='in_store',
        ),
    ]
