# Generated by Django 4.2.4 on 2023-08-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_available_book_in_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
